branches:
  only:
  - master
sudo: required
services: 
- docker
env:
  global:
    - DOCKER_CLIENT_TIMEOUT: 120
    - COMPOSE_HTTP_TIMEOUT: 120
    - MATLAB_USER: datajoint
    - MATLAB_UID: 2000
    - MATLAB_GID: 2000
slim: &slim
  stage: Slim9.9
  os: linux
  language: shell
  script:
    - license=MATLAB_LICENSE_${MATLAB_VERSION}
    - export MATLAB_LICENSE=$(eval echo "\$$license")
    - docker-compose -f LNX-docker-compose.yml up --exit-code-from app
jobs:
  include:
    - <<: *slim
      env:
      - MATLAB_VERSION: R2018b
      - MYSQL_TAG: 8.0
    - <<: *slim
      env:
      - MATLAB_VERSION: R2018b
      - MYSQL_TAG: 5.7
    - <<: *slim
      env:
      - MATLAB_VERSION: R2018b
      - MYSQL_TAG: 5.6
    - <<: *slim
      env:
      - MATLAB_VERSION: R2019a
      - MYSQL_TAG: 8.0
    - <<: *slim
      env:
      - MATLAB_VERSION: R2019a
      - MYSQL_TAG: 5.7
    - <<: *slim
      env:
      - MATLAB_VERSION: R2019a
      - MYSQL_TAG: 5.6